# Generated by Django 5.2.3 on 2025-06-18 04:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                (
                    "profile_picture",
                    models.ImageField(upload_to="media/profile_pictures"),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=20)),
                ("address", models.TextField()),
                ("summary", models.TextField()),
                ("degree", models.CharField(max_length=255)),
                ("institute_name", models.CharField(max_length=255)),
                ("year_of_graduation", models.PositiveIntegerField()),
                ("company_name", models.CharField(max_length=255)),
                ("position", models.CharField(max_length=255)),
                (
                    "years_of_experience",
                    models.DecimalField(decimal_places=1, max_digits=4),
                ),
                ("skills", models.TextField(help_text="Comma-separated skills")),
                ("hobbies", models.TextField(blank=True, null=True)),
                ("achievements", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
